export default {
    
        'gifs': 'Gifs',
        'search': 'Search',
        'categories': 'Categories',
        'loading': 'Loading...',
        'noResults': 'No results found',
        'noCategories': 'No categories found',
        'addCategory': 'Add category',
        'add': 'Add',
        'cancel': 'Cancel',
        'category': 'Category',
        'categoryExists': 'Category already exists',
        'categoryRequired': 'Category is required',
        'categoryMinLength': 'Category must be at least 3 characters long',
        'categoryMaxLength': 'Category must be at most 20 characters long',
        'categoryPattern': 'Category must only contain letters and numbers',
        'categoryInvalid': 'Category is invalid',
        'categoryAdded': 'Category added successfully',
        'categoryNotAdded': 'Category could not be added',
        'categoryDeleted': 'Category deleted successfully',
        'categoryNotDeleted': 'Category could not be deleted',
        'categoryUpdated': 'Category updated successfully',
        'categoryNotUpdated': 'Category could not be updated',
        'categoryNotFound': 'Category not found',
        'categoryNotValid': 'Category is not valid',
        'categoryNotValidForUpdate': 'Category is not valid for update',
        'categoryNotValidForDelete': 'Category is not valid for delete',
        'categoryNotValidForAdd': 'Category is not valid for add',
        'categoryNotValidForSearch': 'Category is not valid for search',
        'categoryNotValidForGet': 'Category is not valid for get',
    }