//Definir mensajes para el idioma inglés

export default  {
        'gifs': 'Gifs',
        'search': 'Buscar',
        'categories': 'Categorías',
        'loading': 'Cargando...',
        'noResults': 'No se encontraron resultados',
        'noCategories': 'No se encontraron categorías',
        'addCategory': 'Agregar categoría',
        'add': 'Agregar',
        'cancel': 'Cancelar',
        'category': 'Categoría',
        'categoryExists': 'La categoría ya existe',
        'categoryRequired': 'La categoría es requerida',
        'categoryMinLength': 'La categoría debe tener al menos 3 caracteres',
        'categoryMaxLength': 'La categoría debe tener como máximo 20 caracteres',
        'categoryPattern': 'La categoría solo debe contener letras y números',
        'categoryInvalid': 'La categoría es inválida',
        'categoryAdded': 'Categoría agregada correctamente',
        'categoryNotAdded': 'La categoría no pudo ser agregada',
        'categoryDeleted': 'Categoría eliminada correctamente',
        'categoryNotDeleted': 'La categoría no pudo ser eliminada',
        'categoryUpdated': 'Categoría actualizada correctamente',
        'categoryNotUpdated': 'La categoría no pudo ser actualizada',
        'categoryNotFound': 'Categoría no encontrada',
        'categoryNotValid': 'La categoría no es válida',
        'categoryNotValidForUpdate': 'La categoría no es válida para actualizar',
        'categoryNotValidForDelete': 'La categoría no es válida para eliminar',
        'categoryNotValidForAdd': 'La categoría no es válida para agregar',
        'categoryNotValidForSearch': 'La categoría no es válida para buscar',
        'categoryNotValidForGet': 'La categoría no es válida para obtener',
    }

